#!/bin/bash

	## Create boot entry with efibootmgr
	EFI_install() {
		echo "------------> Installing efibootmgr <------------"
		chroot "${MOUNTPOINT}" /bin/bash -x <<-EOCHROOT
			## Install efibootmgr
			#${APT} install -y efibootmgr
			
			## Create backup boot EFI # TODO: when doing generate ZBM for the second+ time, copy the last as -backup?
			cp /boot/efi/EFI/ZBM/vmlinuz-bootmenu /boot/efi/EFI/ZBM/vmlinuz-bootmenu-BACKUP
			cp /boot/efi/EFI/ZBM/initramfs-bootmenu.img /boot/efi/EFI/ZBM/initramfs-bootmenu-BACKUP.img
			efibootmgr -c -d "$DISK" -p "$BOOT_PART" \
				-L "ZFSBootMenu (Backup)" \
				-l '\EFI\ZBM\vmlinuz-bootmenu-BACKUP' \
				-u "ro initrd=\EFI\ZBM\initramfs-bootmenu-BACKUP.img quiet"
			
			## Create main boot EFI
			efibootmgr -c -d "$DISK" -p "$BOOT_PART" \
				-L "ZFSBootMenu" \
				-l '\EFI\ZBM\vmlinuz-bootmenu' \
				-u "ro initrd=\EFI\ZBM\initramfs-bootmenu.img quiet"
			
			sync
			sleep 1
		EOCHROOT
	}