#!/bin/bash

## Get the absolute path to the current script directory
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

## Ensure at least one argument is provided
if [[ $# -eq 0 ]]; then
	echo "Error: missing command/argument for 'zorra'"
	echo "Enter 'zorra --help' for usage"
	exit 1
fi

## Parse the top-level command
command="$1"
shift 1

## Dispatch command
case "${command}" in
	debootstrap-install)
		"${script_dir}/debootstrap-install.sh" "$@" || {
			echo "Error: Failed to execute '${command}'."
			exit 1
		}
	;;
	refind)
		"${script_dir}/refind/refind.sh" "$@" || {
			echo "Error: Failed to execute '${command}'."
			exit 1
		}
	;;
	zfs)
		"${script_dir}/zfs/zfs.sh" "$@" || {
			echo "Error: Failed to execute '${command}'."
			exit 1
		}
	;;
	zfsbootmenu)
		"${script_dir}/zfsbootmenu/zfsbootmenu.sh" "$@" || {
			echo "Error: Failed to execute '${command}'."
			exit 1
		}
	;;
	setup)
		"${script_dir}/setup/setup.sh" "$@" || {
			echo "Error: Failed to execute '${command}'."
			exit 1
		}
	;;
	--help|"")
		cat "${script_dir}/usage.txt"
	;;
	*)
		echo "Error: unrecognized command 'zorra ${command}'"
		echo "Enter 'zorra --help' for usage"
		exit 1
	;;
esac