#!/bin/bash

## Get the absolute path to the current script directory
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#3 Parse the top-level command
command="$1"
shift 1

## Dynamically build the current and sub dir paths for the script
cur_dir_script_path="$script_dir/$command.sh"
sub_dir_script_path="$script_dir/$command/$command.sh"

## Check if the script exists in the current or sub dir
if [[ -x "$cur_dir_script_path" ]]; then
	"$cur_dir_script_path" "$@"
elif [[ -x "$sub_dir_script_path" ]]; then
	"$sub_dir_script_path" "$@"
else
	## Throw error
	if [[ -z $command ]]; then
		echo "Missing command"
	else
		echo "Command not found: $command"
	fi

	## Show usage file
	base_dir="$script_dir"
	while [[ "$(basename "$base_dir")" != "zorra" ]]; do
		base_dir=$(dirname "$base_dir")
	done
	echo "For usage, see:"
	cat "${base_dir}/usage.txt"

	exit 1
fi