## TODO: check if KEYFILE has contents, not if keystore is mounted
safe_generate_initramfs(){
	## Check if keystore is mounted, as without it an unbootable intitramfs will be created!
	if [[ -f "${keyfile}" && -s "${keyfile}"  ]]; then
		## Reload systemd deamon to (re)load any mount units generated by zfs-mount-generator via /etc/zfs/zfs-list.cache/<poolname>
		systemctl daemon-reload

		## Update initramfs (ignoring warning about swap using keyfile)
		update-initramfs -c -k all 2>&1 | grep -v "cryptsetup: WARNING: Resume target swap uses a key file"
	else
		local keystore_dataset=$(zfs list -o name | grep keystore)
		cat <<-EOF

			The keystore (${keystore_dataset}) is not mounted. Generating a new initramfs will create an unbootable system!
			Make sure ${keystore_dataset} is mounted at '${keyfile}'.

		EOF
		exit 1
	fi
}
