#!/bin/bash
set -e

# Path to dropbear authorized_keys file
dropbear_authorized_keys="/etc/dropbear/authorized_keys"













## Only execute manager steps when not doing a debootstrap-install, otherwise stuff is installed on live environment
if ! ${debootstrap_install}; then
	## Execution order
	if ${clear_authorized_keys}; then
		clear_authorized_keys
	fi

	if ${add_authorized_key}; then
		add_authorized_key
	fi

	if ${setup_remote_access}; then
		clean_authorized_keys
		setup_remote_access
	fi

	if ${set_refind_theme}; then
		set_refind_theme
	fi

	if ${set_zbm_timeout}; then
		set_zbm_timeout
	fi

	if ${set_refind_timeout}; then
		set_refind_timeout
	fi

	if ${auto_unlock_pool}; then
		auto_unlock_pool
	fi

	if ${change_key}; then
		change_key
	fi

	if ${update_zfsbootmenu}; then
		update_zfsbootmenu
	fi
fi